### ISSUE TITLE
skolelinux Debian Edu 11 Bullseye(Ltsp)

### ISSUE THREAD

**Issue by Abu-Hadi** [alkisg/alkisg.github.io#1]
hi 
i am new to LTSP i have setup a small lab of 50 clients with skolelinux edu 11 bullseye installed on server every thing is working fine but the problem is when in install software on ltsp server (chrootless) and after applying ("sudo debian-edu-ltsp-install --diskless_workstation yes") clients not showing newly installed softwares i have "fat clients" and "chrootless setup".
i need help 
regard Abu Hadi

**Comment by alkisg** [comment]
Hi @Abu-Hadi, you started this discussion in the wrong place, please go there instead:

https://github.com/ltsp/ltsp/discussions
